version: '3.8'

services:
  backend:
    build: ./backend
    container_name: youtube-backend
    ports:
      - "4000:4000"
    networks:
      - youtube-net
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: youtube-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    networks:
      - youtube-net



networks:
  youtube-net:
    driver: bridge
