apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: shadow-devops
type: Opaque
stringData:
  PORT: "4000"
  GOOGLE_SERVICE_ACCOUNT_KEY_PATH: "./service-account.json"
  GOOGLE_SHEETS_ID: "1_BMGDei0pE4ZkvHpHe_pJlD9cJVgUcVOxmzrLQBh6_0"
  YOUTUBE_API_KEY: "AIzaSyDcsTotu2LpQFO6PpkyO4j7qNt9-vxsq6w"
  OPENAI_API_KEY: "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"
  OPENAI_MODEL: "gpt-4o-mini"
  BACKEND_SECRET: "mysecret123"
