name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug secrets
        run: |
          echo "DockerHub user: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Check Google JSON secret exists: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON != '' }}"

      # Buat file service-account.json dari secret
      - name: Create service-account.json
        run: |
          mkdir -p backend
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > backend/service-account.json
          echo " Created service-account.json"

      # Build Backend Docker image
      - name: Build backend Docker image
        run: |
          docker build -f backend/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/youtube-backend:latest backend

      # Build Frontend Docker image
      - name: Build frontend Docker image
        run: |
          docker build -f frontend/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/youtube-frontend:latest frontend

      # Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push image
      - name: Push images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/youtube-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/youtube-frontend:latest
