name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js untuk build frontend dan backend
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Build Backend
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Build backend Docker image
        working-directory: ./backend
        run: |
          echo "=== DEBUG: Username is -> ${{ secrets.DOCKERHUB_USERNAME }} ==="
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "‚ùå ERROR: DOCKERHUB_USERNAME secret kosong atau tidak terbaca!"
            exit 1
          fi
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/youtube-backend:latest .

      # Build Frontend
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend Docker image
        working-directory: ./frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/youtube-frontend:latest .

      # Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #  Push images ke Docker Hub
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/youtube-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/youtube-frontend:latest

      
